### ISSUE TITLE
Option to merge when re-importing table

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3506] opened 2019-07-05 16:16 UTC
I'm not sure if this is a new issue or if the import has always worked like this, but when I re-import an existing table from a .sav  file any attributes or annotations that have been created in the table are lost.

To reproduce:
Upload a .sav file to a project and import it:
https://opal-demo.obiba.org/ui/index.html#!project;name=CaG;tab=TABLES

Once the upload has complete edit a few variables creating Raw attributes and Annotations.

Re-import the file again, all create attributes and annotations are lost.

I tried this with and without the incremental checkbox ticked. Is this by design, if so do we need a merge option as well?

**Comment by ymarcon** [comment] 2019-07-05 16:40
This is a feature, not a bug. The import wizard should have shown you that there are modified variables. If your plan is to import data periodically, then make a view other it and annotate the view instead of the raw table.

**Comment by sam-story** [comment] 2019-07-22 11:58
Following our discussion today, the option to merge attributes on import would solve a lot of other issues.

This would need a UI and WebService flag (default = false).

If true, existing attributes (with and without namespace) and properties (Unit, Referenced Entity Type etc) would be merged. E.g.
- New attributes would be added
- Existing attributes and properties not in the import file would remain
- Modified attributes would have the change applied

**Comment by ymarcon** [comment] 2019-07-31 07:53
Note there are some properties that cannot be "merged":
* name (of course)
* value type, because it affects the database schema
* repeatable, because it affects the database schema

**Closed** 2019-11-04 20:39 UTC
Labels: ALSPAC, improvement, new feature
